import Head from "next/head";
import Link from "next/link";

function ForgotPassword() {
  return (
    <>
      <div className="d-flex justify-content-center">
        <Head>
          <title>Forgot Password</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={"text-center mt-5 mainWidth"}>
          <form>
            <h1 className="mt-4 flex h3 mb-3 fw-normal">Trouble Logging In?</h1>
            <div className="mt-5 flex">
              <p>
                Enter your email, phone, or username and we'll send you a link
                to get back into your account.
              </p>
            </div>

            <div className="form-floating d-flex justify-content-center">
              <input
                type="Phonenumber"
                className={"form-control formField"}
                id="floatingInput"
                placeholder="number"
              />
              <label htmlFor="floatingInput">
                Phone number,username or email
              </label>
            </div>
            <button className="btn signinBtn mt-4 flex">
              {" "}
              Send Reset Link
            </button>
          </form>
          <div className="mt-4 flex">
            <Link href="/signup">
              <a className={""}> Create New Account</a>
            </Link>
          </div>
          <h3 className="mt-4 flex h3 mb-3 fw-normal">Do you Remember?</h3>
          <div>
            <Link href="/">
              <a className={""}>Back to Sign in page</a>
            </Link>
          </div>
        </main>
      </div>
    </>
  );
}

export default ForgotPassword;
